### ISSUE TITLE
Invalid configuration - no broker provided

### ISSUE THREAD

**Issue by cptcanuck** [vsouza/go-kafka-example#1]
I grabbed your code to play with, and it doesn't work out of the box (anymore?).  

When I try and run it as is:
`go run cmd/producer/main.go --brokerList "kafka01:9092" --topic test-1`

panic: kafka: invalid configuration (You must provide at least one broker address)

goroutine 1 [running]:
main.main()
	/git/go-kafka-example/cmd/producer/main.go:24 +0x2f3
exit status 2`

I'm opening this issue so that I have a ticket number for the the branch - the fix is easy, just needed to add
`kingpin.Parse()` in main()

PR incoming for you if you want it.

**Comment by vsouza** [comment]
@cptcanuck thanks for reporting. 👍
