### ISSUE TITLE
Goka Logo

### ISSUE THREAD

**Issue by ubunatic** [vsouza/go-kafka-example#4]
Hi Vinicius!
We appreciate that you like the [Goka](https://github.com/lovoo/goka) logo, which LOVOO published on
https://tech.lovoo.com/2017/05/23/goka at 2017-05-23.

Please do not claim this Logo for your project and remove `header.png` from the repository.

Thank you!

Uwe Jugel,
Lead Data Engineering at LOVOO

**Comment by vsouza** [comment]
@ubunatic Removed.
